name: flutter_shop
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  google_fonts: ^2.3.1
  http: ^0.13.0
  shared_preferences: ^2.0.13
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
#  #map
#  google_maps_flutter: ^2.0.1
#  flutter_google_places: ^0.3.0
#  #firebase
  firebase_core: ^1.2.1
  cloud_firestore: ^3.1.14
  firebase_storage: ^10.2.15
  firebase_auth: ^1.0.0
#  google_sign_in: 5.0.0
#  #image
  image_picker: ^0.8.5
#  image_gallery_saver: ^1.6.8
#  multi_image_picker: ^4.8.0
  #bloc
  flutter_bloc: ^7.0.0
  #provider
#  provider: ^5.0.0-nullsafety.5
#  #payment
#  square_in_app_payments: ^1.6.0
  #data
  equatable: ^2.0.0
#  meta: ^1.1.6
#  intl: ^0.17.0
  rxdart: ^0.26.0
#  #UI
#  flutter_spinkit: ^5.0.0
#  carousel_slider: ^4.0.0-nullsafety.0
  shimmer: ^2.0.0-nullsafety.0
  #Others
#  shared_preferences: ^2.0.15
#  uuid: ^3.0.3
#  fluttertoast: ^8.0.3
#  dio: ^4.0.0
#  url_launcher: ^6.0.3
#  dropdown_search: ^0.6.1
#  platform: ^3.1.0
#  # The following adds the Cupertino Icons font to your application.
#  # Use with the CupertinoIcons class for iOS style icons.
#  cupertino_icons: ^1.0.0
  #flutter_svg: ^0.21.0-nullsafety.0 # Help us to use svg in our app
  flutter_svg: ^1.0.3
#  flutter_launcher_icons: ^0.9.0
#  path_provider: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/locale/

  # To add custom fonts to your application, add a fonts section here,
#  fonts:
#    - family: Roboto
#      fonts:
#        - asset: assets/fonts/roboto/Roboto-Regular.ttf
#          weight: 400
#        - asset: assets/fonts/roboto/Roboto-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/roboto/Roboto-Bold.ttf
#          weight: 600
#    - family: Poppins
#      fonts:
#        - asset: assets/fonts/poppins/Poppins-Regular.otf
#          weight: 400
#        - asset: assets/fonts/poppins/Poppins-Medium.otf
#          weight: 500
#        - asset: assets/fonts/poppins/Poppins-SemiBold.otf
#          weight: 600
